/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CabInformation;
import Business.Car;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rhnye
 */
public class CreateNewEntryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewEntryJPanel
     */
private JPanel userProcessContainer;
private CabInformation cabInformation;

    CreateNewEntryJPanel(JPanel userProcessContainer, CabInformation cabInformation) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.cabInformation = cabInformation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBrandName = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtMinSeats = new javax.swing.JTextField();
        txtMaxSeats = new javax.swing.JTextField();
        txtManufacterYear = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        chkboxYesMaintenance = new javax.swing.JCheckBox();
        chkboxNoMaintenance = new javax.swing.JCheckBox();
        checkboxYesAvailable = new javax.swing.JCheckBox();
        checkboxNoAvailable = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Car Details");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnBack.setText("<<back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Brand Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Model Number:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Serial Number:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Minimum Seats:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Maximum Seats:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Manufactered Year:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Maintenance Certificate:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Available:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Available City:");

        buttonGroup3.add(chkboxYesMaintenance);
        chkboxYesMaintenance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chkboxYesMaintenance.setText("Yes");
        chkboxYesMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxYesMaintenanceActionPerformed(evt);
            }
        });

        buttonGroup3.add(chkboxNoMaintenance);
        chkboxNoMaintenance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chkboxNoMaintenance.setText("No");

        buttonGroup4.add(checkboxYesAvailable);
        checkboxYesAvailable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkboxYesAvailable.setText("Yes");

        buttonGroup4.add(checkboxNoAvailable);
        checkboxNoAvailable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkboxNoAvailable.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnBack)
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreate)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBrandName, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addComponent(txtModelNumber)
                                        .addComponent(txtSerialNumber))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtMinSeats, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                        .addComponent(txtMaxSeats, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                        .addComponent(txtManufacterYear, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkboxYesMaintenance)
                                .addGap(18, 18, 18)
                                .addComponent(chkboxNoMaintenance))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkboxYesAvailable)
                                .addGap(18, 18, 18)
                                .addComponent(checkboxNoAvailable))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtManufacterYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chkboxYesMaintenance)
                    .addComponent(chkboxNoMaintenance))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(checkboxYesAvailable)
                    .addComponent(checkboxNoAvailable))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnCreate)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        Component [] compos = this.userProcessContainer.getComponents();
        for (Component comp: compos) {
            if (comp instanceof ManageCarJPanel) {
                ManageCarJPanel panel = (ManageCarJPanel) comp;
                panel.populateTable(cabInformation, "carDetails");
                
            }
            
        }
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
            
        String brandName = txtBrandName.getText();
        if(brandName == null || brandName.equals("")){
                JOptionPane.showMessageDialog(null, "Please enter the Brand Name");
                return;
            }
        
        //int makeYear = Integer.parseInt(txtMakeYear.getText());
        String manufYear = txtManufacterYear.getText();
        if(manufYear == null || manufYear.equals("")){
                JOptionPane.showMessageDialog(null, "Please enter the Manufacturing Year");
                return;}
         try{
                Double.parseDouble(txtManufacterYear.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter Number for Manufacturing Year");
            }
        
        //int minSeats = Integer.parseInt(txtMinSeats.getText());
        String minSeats = txtMinSeats.getText();
        if(minSeats == null || minSeats.equals("")){
                JOptionPane.showMessageDialog(null, "Please enter the Minimum Seats");
                return;}
         try{
                Double.parseDouble(txtMinSeats.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter Number for Minimum Seats");
            }
        
        //int maxSeats = Integer.parseInt(txtMaxSeats.getText());
        String maxSeats = txtMaxSeats.getText();
        if(maxSeats == null || maxSeats.equals("")){
                JOptionPane.showMessageDialog(null, "Enter the Maximum Number of Seats");
                return;}
        try{
                Double.parseDouble(txtMaxSeats.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter Number for Maximum Seats");
            }
       // int serialNum = Integer.parseInt(txtSerialNum.getText());
        String serialNum = txtSerialNumber.getText();
        if(serialNum == null || serialNum.equals("")){
                JOptionPane.showMessageDialog(null, "Please Enter the Serial Number");
                return;}
        try{
                Double.parseDouble(txtSerialNumber.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter Number for Serial Number");
            }
        
        String modelNumber = txtModelNumber.getText();
        if(modelNumber == null || modelNumber.equals("")){
                JOptionPane.showMessageDialog(null, "Enter the Model Name");
                return;
            }
        String city= txtCity.getText();
        if(city == null || city.equals("")){
                JOptionPane.showMessageDialog(null, "Please Enter the City");
                return;
            }
        if(checkboxYesAvailable.isSelected() == false && checkboxNoAvailable.isSelected()==false){
                JOptionPane.showMessageDialog(null, "Please select Yes or No checkbox for Availibilty");
                return;
            }
        if(chkboxYesMaintenance.isSelected() == false && chkboxNoMaintenance.isSelected()==false){
                JOptionPane.showMessageDialog(null, "Please select Yes or No checkbox for Maintenance Certificate");
                return;
            }

        
        
        Car car = cabInformation.addCar();
        car.setBrand(brandName);
        car.setModel_num(modelNumber);
        car.setAvailable_city(city);
        car.setManufactured_year(Integer.parseInt(txtManufacterYear.getText()));
        car.setMin_seats(Integer.parseInt(txtMinSeats.getText()));
        car.setMax_seats(Integer.parseInt(txtMaxSeats.getText()));
        car.setSerial_num(Integer.parseInt(txtSerialNumber.getText()));
        car.setAvailable(checkboxYesAvailable.isSelected());
        car.setMaintenance_certificate(chkboxYesMaintenance.isSelected());
        
        
        JOptionPane.showMessageDialog(null, "Uber Service Created Successfully");
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void chkboxYesMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxYesMaintenanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkboxYesMaintenanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox checkboxNoAvailable;
    private javax.swing.JCheckBox checkboxYesAvailable;
    private javax.swing.JCheckBox chkboxNoMaintenance;
    private javax.swing.JCheckBox chkboxYesMaintenance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManufacterYear;
    private javax.swing.JTextField txtMaxSeats;
    private javax.swing.JTextField txtMinSeats;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
