/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CabInformation;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rhnye
 */
public class UberServicesWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UberServicesWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private CabInformation cabInformation;

    UberServicesWorkAreaJPanel(JPanel userProcessContainer, CabInformation cabInformation) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.cabInformation = cabInformation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateNewEntry = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        btnCreateNewEntry.setBackground(new java.awt.Color(102, 102, 102));
        btnCreateNewEntry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCreateNewEntry.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateNewEntry.setText("Create New Entry");
        btnCreateNewEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewEntryActionPerformed(evt);
            }
        });

        btnManage.setBackground(new java.awt.Color(102, 102, 102));
        btnManage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManage.setForeground(new java.awt.Color(255, 255, 255));
        btnManage.setText("Manage Cars");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnCreateNewEntry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(btnManage, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateNewEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addContainerGap(430, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        // TODO add your handling code here:
        ManageCarJPanel panel = new ManageCarJPanel(userProcessContainer, cabInformation);
        userProcessContainer.add("ManageCarJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnCreateNewEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewEntryActionPerformed
        // TODO add your handling code here:
        CreateNewEntryJPanel panel = new CreateNewEntryJPanel(userProcessContainer, cabInformation);
        userProcessContainer.add("CreateNewEntryJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateNewEntryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNewEntry;
    private javax.swing.JButton btnManage;
    // End of variables declaration//GEN-END:variables
}
